spring:
    application:
      name: project-api
       
    jpa: 
      hibernate:
        ddl-auto: update
        show_sql: true
        use_sql_comments: true
        fotmat_sql: true
        
    datasource:
      url: jdbc:mysql://localhost:3306/sw
      username: sangmin
      password: tkdals12
      driver-class-name: com.mysql.jdbc.Driver
      hikari:
        maximum-pool-size: 2
         