spring:
    application:
      name: project-api
       
## Hibernate Properties
# The SQL dialect makes Hibernate generate better SQL for the chosen database
    jpa: 
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
# Hibernate ddl auto (create, create-drop, validate, update)
      hibernate:
        ddl-auto: update
        
    datasource:
      url: jdbc:mysql://localhost:3306/sw?useSSL=false
      username: sangmin
      password: tkdals12
      driver-class-name: com.mysql.jdbc.Driver
      hikari:
        maximum-pool-size: 2

server:
  port: 8001